In [2]:
import pandas as pd
import os

### getting the file lists

In [3]:
# setting the data directory
data_dir = '../../AI_perception_survey_data/WE'

In [4]:
# getting all file names
all_files = os.listdir(data_dir)

In [5]:
all_files

['Public Perception of Artificial Intelligence Technologies [UK].csv',
 'Public Perception of Artificial Intelligence Technologies [Deutsche].csv',
 'Pollfish_Survey_%C3%96ffentliche_Wahrnehmung_der_k%C3%BCnstlichen_Intelligenz_%5BDeutsche%5D_1979903.xlsx',
 'Public Perception of Artificial Intelligence Technologies [intl_Ver].csv',
 "Perception Publique des technologies de l'Intelligence Artificielle [FR].csv",
 'gm_all.csv',
 'Pollfish_Survey_Perception_Publique_des_technologies_de_l%27Intelligence_Artificielle_%5BFR%5D_1979900.xlsx']

In [6]:
# extracting the pollfish ones
pf_files = [file for file in all_files if file.split('_')[0] == 'Pollfish']

In [8]:
pf_files

['Pollfish_Survey_%C3%96ffentliche_Wahrnehmung_der_k%C3%BCnstlichen_Intelligenz_%5BDeutsche%5D_1979903.xlsx',
 'Pollfish_Survey_Perception_Publique_des_technologies_de_l%27Intelligence_Artificielle_%5BFR%5D_1979900.xlsx']

In [101]:
# loading all files in
pf_de = pd.read_excel(os.path.join(data_dir, pf_files[0]), sheet_name = 'Individuals')
pf_fr = pd.read_excel(os.path.join(data_dir, pf_files[1]), sheet_name = 'Individuals')

In [102]:
# taking a brief look
pf_fr.head()

,ID,Time Started,Time Finished,Manufacturer,OS,Country,Area,City,Provider,Gender,...,Gamer,Value Shopper,Food and Dining Lover,Entertainment Enthusiast,Fashionista,Job Seeker,Insurance,Real Estate,Car Purchase,Unnamed: 65
0,467934861,2019-05-17 08:12:35,2019-05-17 08:17:29,OnePlus,Android,FR,Brittany,Miniac-Morvan,Bouygues,male,...,True,True,True,True,False,NaN,NaN,NaN,NaN,NaN
1,-1953996334,2019-05-17 08:25:55,2019-05-17 08:27:54,Huawei,Android,FR,Île-de-France,Paris,Bouygues,male,...,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN
2,873807755,2019-05-17 08:16:32,2019-05-17 08:22:48,Unknown,Android,FR,Nouvelle-Aquitaine,Agen,SFR,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-1008838748,2019-05-17 08:22:18,2019-05-17 08:26:14,Unknown,Web,FR,Île-de-France,Paris,NaN,female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-920061686,2019-05-17 08:12:58,2019-05-17 08:14:22,Unknown,iOS,BE,Flanders,Ghent,NaN,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

We have a lot of extra cols that might be interesting in other cases but for reason of uniformity we'll not need them for this analysis

### cleaning, renaming and reordering columns

In [103]:
# seeing which cols to keep
for i, col in enumerate(pf_fr.columns):
    print('*******************', i, '*******************')
    print(col)
    print(' ')

******************* 0 *******************
ID

******************* 1 *******************
Time Started

******************* 2 *******************
Time Finished

******************* 3 *******************
Manufacturer

******************* 4 *******************
OS

******************* 5 *******************
Country

******************* 6 *******************
Area

******************* 7 *******************
City

******************* 8 *******************
Provider

******************* 9 *******************
Gender

******************* 10 *******************
Age

******************* 11 *******************
Year Of Birth

******************* 12 *******************
Comment évalueriez-vous votre connaissance personnelle des technologies d'intelligence artificielle ?

******************* 13 *******************
Parmi les affirmations suivantes, lesquelles sont * fausses * concernant la nature ou les capacités de l'intelligence artificielle ?

******************* 14 *******************
Avez-vous été servi par ou utilisé des technologies d'intelligence artificielle ?

******************* 15 *******************
Sur une échelle de 1 à 7, comment évalueriez-vous l’impact des technologies de l’intelligence artificielle sur la SOCIÉTÉ [AUJOURD'HUI] ?

******************* 16 *******************
Et dans les 10 prochaines années?

******************* 17 *******************
Sur une échelle de 1 à 7, comment évalueriez-vous L'AMPLITUDE de l'impact de l'IA [AUJOURD'HUI]?

******************* 18 *******************
Et dans les 10 prochaines années?.1

******************* 19 *******************
Sur une échelle de 1 à 7, comment évalueriez-vous l'impact actuel de l'intelligence artificielle sur le travail pour vous?

******************* 20 *******************
Et dans les 10 prochaines années?.2

******************* 21 *******************
Selon vous, dans votre vie professionnelle, quels bénéfices technologiques seront permis par l'intelligence artificielle ? Merci de spécifier si d'autres

******************* 22 *******************
Selon vous, dans votre vie professionnelle, quels aspects souffriront le plus des technologies de l'intelligence artificielle? Merci de spécifier si d'autres

******************* 23 *******************
Sur une échelle de 1 à 7, comment évalueriez-vous l’impact actuel de l’intelligence artificielle sur votre vie personnelle?

******************* 24 *******************
Et dans les 10 prochaines années

******************* 25 *******************
Parmi les suivants, quels aspects de votre vie personnelle bénéficieront le plus de l'IA ? Merci de spécifier si d'autres

******************* 26 *******************
Parmi les suivants, quels aspects de votre vie personnelle souffriront le plus de l'IA ? Merci de spécifier si d'autres

******************* 27 *******************
Avec lequel des énoncés suivants êtes-vous le plus d'accord?

******************* 28 *******************
Pensez-vous que vous risquez d'être remplacé par une intelligence artificielle?

******************* 29 *******************
Veuillez sélectionner 3 emplois dans la liste ci-dessous qui, selon vous, risquent d'être remplacés par des applications d'Intelligence Artificielle dans les 10 prochaines années

******************* 30 *******************
Parmi les aspects suivants, quelles caractéristiques rendent un emploi remplaçable par l'IA? Si d'autres, veuillez préciser

******************* 31 *******************
Faites-vous confiance aux applications d'intelligence artificielle?

******************* 32 *******************
Lesquels des facteurs suivants correspond le mieux à vos raisons de méfiance? si d'autres, veuillez spécifier

******************* 33 *******************
Quelle est votre profession / domaine d’expertise (étudiant en histoire d'art,  pathologue, ingénieur métallurgique, mécanicienne, etc.)?

******************* 34 *******************
Quelle est votre plus haute qualification en éducation?

******************* 35 *******************
Possédez-vous un smart phone?

******************* 36 *******************
Sur une échelle de 1 à 7, comment sera la vie dans 10 ans?

******************* 37 *******************
Marital Status

******************* 38 *******************
Number of children

******************* 39 *******************
Education

******************* 40 *******************
Employment Status

******************* 41 *******************
Career

******************* 42 *******************
Race

******************* 43 *******************
Income

******************* 44 *******************
Postal Code

******************* 45 *******************
US Census Region

******************* 46 *******************
US Census Division

******************* 47 *******************
US Congressional District

******************* 48 *******************
DMA Code

******************* 49 *******************
DMA Name

******************* 50 *******************
Musicfan

******************* 51 *******************
Productivity Booster

******************* 52 *******************
Bookworm

******************* 53 *******************
Socialite

******************* 54 *******************
Traveler

******************* 55 *******************
Sportsfan

******************* 56 *******************
Gamer

******************* 57 *******************
Value Shopper

******************* 58 *******************
Food and Dining Lover

******************* 59 *******************
Entertainment Enthusiast

******************* 60 *******************
Fashionista

******************* 61 *******************
Job Seeker

******************* 62 *******************
Insurance

******************* 63 *******************
Real Estate

******************* 64 *******************
Car Purchase

******************* 65 *******************
Unnamed: 65

In [104]:
# selecting which cols to keep
cols_to_keep_fr = list(pf_fr.columns[12:37]) + [pf_fr.columns[5]] + [pf_fr.columns[10]]
cols_to_keep_de = list(pf_de.columns[12:37]) + [pf_de.columns[5]] + [pf_de.columns[10]]

In [105]:
# slimming the dfs down
pf_fr = pf_fr[cols_to_keep_fr]
pf_de = pf_de[cols_to_keep_de]

In [114]:
# new col names
cols_renamed = sorted(['q{:02}'.format(i+1) for i in range(21)] + ['q{:02}'.format(i+1) for i in range(27,31)] + ['q25', 'q26_sup'])

In [115]:
# renaming cols
pf_fr.columns = cols_renamed
pf_de.columns = cols_renamed

### recoding answers

In [116]:
pf_fr.head(3)

,q01,q02,q03,q04,q05,q06,q07,q08,q09,q10,...,q18,q19,q20,q21,q25,q26_sup,q28,q29,q30,q31
0,J'en sais beaucoup sur le sujet,L’architecture du réseau neuronal récurrent ri...,Oui,5,6,5,7,5,7,Nouvelles opportunités commerciales;Meilleure ...,...,Comptables et auditeurs;Opérateurs téléphoniqu...,Les compétences requises pour le travail sont ...,Oui,L'incapacité de l'IA à comprendre les nuances ...,Ingénieur métallurgique,Bachelor/BTS ou équivalent,Oui,6,FR,18 - 24
1,J'en sais beaucoup sur le sujet,L’IA peut rédiger des articles de qualité huma...,Oui,7,7,6,7,7,7,Nouvelles opportunités commerciales;Augmentati...,...,Data scientists;Opérateurs téléphoniques;Ensei...,Les compétences requises pour le travail sont ...,Oui,L'incapacité de l'IA à comprendre les nuances ...,Ingénieur,"Doctorat, son équivalent ou supérieur",Oui,7,FR,18 - 24
2,J'en ai entendu parler mais je ne suis pas sur...,L'IA n'est capable d'effectuer qu'une gamme li...,Peut-être,4,6,4,6,4,6,aucun,...,Data scientists;Opérateurs téléphoniques,Manque de créativité,Peut-être,L'IA peut être biaisée et renforcer l'injustic...,Sans profession,Diplôme d'études secondaires ou l'équivalent,Oui,5,FR,45 - 54

The seperators are '|', whereas our recoding function uses ';' as the default seperator, we need to replace

In [92]:
# noting question numbers that need recoding

# multiple choice
q_num_mc = [2,10,11,14,15,18,19,21,24]
q_num_mc = ['q{:02}'.format(num) for num in q_num_mc]
# single choice
q_num_sc = [1,3,16,17,20,22,23,25,27,28]
q_num_sc = ['q{:02}'.format(num) for num in q_num_sc]
# all
q_num_all = q_num_mc + q_num_sc

In [110]:
# replacing '|' with ';'
for q_num in q_num_mc:
    if q_num in pf_fr.columns:
        pf_fr[q_num] = [ans.replace(' | ', ';') for ans in pf_fr[q_num]]
        pf_de[q_num] = [ans.replace(' | ', ';') for ans in pf_de[q_num]]

### recoding

In [118]:
# importing the recoding function
from clean_functions import recode_answers